
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nexus
  namespace: nexus
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sonatype-nexus
    version: 3.15.2-01
  values:
    env:
      nexusDockerHost: docker-containers-nexus.insights.bose.com
      nexusHttpHost: nexus.insights.bose.com

      #nexusBackup:
      #  env:
      #    targetBucket: "gs://my-nexus-backup"
      #  persistence:
      #    storageClass: standard

 #ingress:
 #  enabled: true
 #  annotations:
 #    kubernetes.io/ingress.class: gce
 #    kubernetes.io/tls-acme: true

  persistence:
    storageClass: standard
    storageSize: 1024Gi

  resources:
    requests:
      cpu: 250m
      # Based on https://support.sonatype.com/hc/en-us/articles/115006448847#mem
      # and https://twitter.com/analytically/status/894592422382063616:
      #   Xms == Xmx
      #   Xmx <= 4G
      #   MaxDirectMemory >= 2G
      #   Xmx + MaxDirectMemory <= RAM * 2/3 (hence the request for 4800Mi)
      #   MaxRAMFraction=1 is not being set as it would allow the heap
      #     to use all the available memory.
      memory: 4800Mi
